global:
  scrape_interval: 5s

scrape_configs:
- job_name: cadvisor
  static_configs:
    - targets:
      - cadvisor:8080

- job_name: node
  static_configs:
    - targets:
      - node-exporter:9100