version: '3'

services:
  nginx:
    image: nginx:1.25.1-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env.nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw