version: '3'

volumes:
  certbot-etc:

services:
  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - certbot-etc:/etc/letsencrypt:ro
    depends_on:
      - web
  
  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./cloudflare.ini:/root/cloudflare.ini:ro
      - certbot-etc:/etc/letsencrypt:rw
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email info@togethercrew.com
      --agree-tos --no-eff-email
      --force-renewal
      -d ${SERVER_NAME}
    depends_on:
      - nginx

  web:
    image: yeasy/simple-web:latest
    container_name: web
    restart: always