http:
  routers:
    api:
      rule: "Host(`traefik.{{ env "HOST_NAME" }}`)"
      service: "api@internal"
      tls:
        domains:
          - main: "{{ env "HOST_NAME" }}"
            sans:
              - "*.{{ env "HOST_NAME" }}"
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        usersFile: ./userFile

tls:
  certificates:
    - certFile: /etc/certs/origin-cert.pem
      keyFile: /etc/certs/origin-key.pem
      stores:
        - default