global:
  sendAnonymousUsage: false

providers:
  docker:
    exposedbydefault: false
    watch: true

  file:
    fileName: /etc/traefik/dynamic.yml
    watch: true
          
entryPoints:
  http:
    address: :80    
  https:
    address: :443

metrics:
  prometheus: true

api:
  insecure: false

log:
  level: DEBUG