on: 
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: TogetherCrew/operations/.github/workflows/lint.ts.yml@main
        - uses: ./build.yml
        - uses: ./test.yml
        - uses: ./push.yml