on: 
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true

jobs:
    lint:
      uses: ./.github/workflows/lint.yml
    build:
      uses: ./.github/workflows/build.yml@latest
    test:
      uses: ./.github/workflows/test.yml@latest
    push:
      uses: ./.github/workflows/push.yml@latest