on: 
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true

jobs:
    lint:
      uses: ./.github/workflows/lint.yml
    build:
      needs: lint
      uses: ./.github/workflows/build.yml
    test:
      needs: build
      uses: ./.github/workflows/test.yml
    push:
      needs: test
      uses: ./.github/workflows/push.yml