on: 
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true

jobs:
    lint:
      uses: ./.github/workflows/lint.yml
    test:
      needs: lint
      uses: ./.github/workflows/test.yml
      secrets:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    build-push:
      needs: test
      uses: ./.github/workflows/build-push.yml