on: 
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
    lint:
      uses: ./.github/workflows/lint.yml
      secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build:
      needs: lint
      uses: ./.github/workflows/build.yml
    test:
      needs: build
      uses: ./.github/workflows/test.yml
      secrets:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    push:
      needs: test
      uses: ./.github/workflows/push.yml