on: 
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

#     permissions:
#       pages: write      # to deploy to Pages
#       id-token: write   # to verify the deployment originates from an appropriate source

#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.test.yml up --exit-code-from app
      - uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#       - uses: actions/configure-pages@v3
#       - uses: actions/upload-pages-artifact@v1
#         with:
#           path: './coverage/lcov-report'
#       - uses: actions/deploy-pages@v2
#         id: deployment
